

///////////////////////////////////////////////////////////////////////////////////////////////
/* 	ponder.js
	Code was created by C. Eton. Statement author unknown.  
 
 	Only 1 item need to be edited:

	1.  The Statements array variable.

*///////////////////////////////////////////////////////////////////////////////////////////////



///////////////////////////////////////////////////////////////////////////////////////////////
// List the statements to display.  Add statements as necessary.  


var Statements = new Array(

	'When companies ship Styrofoam what do they pack it in? ', 
	'Why is a carrot more orange than an orange? ', 
	'Why do we label underwear as a pair? ', 
	'What would a chair look like if your knees bent the other way? ', 
	'Why do firehouses have Dalmatians? ', 
	'Why is it called a TV \"set\" when you only get one? ', 
	'Why in a country with freedom of speech are there phone bills? ', 
	'Does the little mermaid wear an algaebra?', 
	'Why do scars never go away? ', 
	'Why don\'t sheep shrink when it rains? ', 
	'Why do old women die their hair blue? ', 
	'Is laughing stock cattle with a sense of humor? ', 
	'Why do they put Braille dots on the keypad of the drive up ATM? ', 
	'Should you trust a stockbroker who\'s married to a travel agent? ', 
	'Why do they report power outages on TV? ', 
	'Why do tugboats push their barges? ', 
	'Sooner or later doesn\'t EVERYONE stop smoking? ', 
	'Why is a keyboard called a keyboard if it just has little buttons? ', 
	'How can someone walk up hill both ways through 32 feet of snow?', 
	'What is the purpose of that little ball on top of the flagpole? ', 
	'If 75% of all accidents occur within 5 miles of home, why not move 10 miles away? ', 
	'Why do your nose run and your feet smell? ', 
	'Will you die if you get scared half to death twice? ', 
	'What is the funny beep on the radio just before the network news? ', 
	'If a vampire can\'t see himself in a mirror, why is his hair always so neat?', 
	'If a cow laughed would milk come out its nose? ', 
	'If 7-11 is open 24 hours a day, 365 days a year, why are there locks on the doors? ', 
	'Why do men\'s bicycles have crossbars? ', 
	'Why is the word abbreviate so long? ', 
	'Do married people live longer than single people do or does it just seem longer?', 
	'Why do they lock gas station bathrooms? Are they afraid someone is going to clean them? ', 
	'Is it true that cannibals don\'t eat clowns because they taste funny? ', 
	'If the funeral procession is at night, do folks drive with their headlights off? ', 
	'Can you be a closet claustrophobic?', 
	'If a parsley farmer is sued can the garnish his wages? ', 
	'If you are in a vehicle going the speed of light, what happens if you turn on your headlights? ', 
	'Isn\'t Disneyland a people trap operated by a mouse? ', 
	'If you keep trying to prove Murphy\'s law, will something go wrong? ', 
	'Do you need a silencer if you are going to shoot a mime?', 
	'Are people born stupid or do they have to work at it?', 
	'How did a fool and his money get together?', 
	'If the cops arrest a mime do they tell him he has the right to remain silent? ', 
	'If you try to fail and succeed which have you done?', 
	'How can someone draw a blank?', 
	'Do toilet seats really protect us from anything?', 
	'Why do they call it quicksand when it sucks you down slowly?', 
	'If quitters never win, and winners never quit, than who is the fool who said, \"Quit while you\'re ahead\"?', 
	'How do you know when it is time to tune your bagpipes?', 
	'If someone with multiple personalities robs a bank who is charged with the crime?', 
	'Corn oil is made from corn, Olive oil is made from olives, so what does baby oil come from?', 
	'How can there be self-help groups?', 
	'If the land is free, why is someone always trying to sell me something?', 
	'Why are movie theatres always so cold? ', 
	'If fire fighters fight fires and crime fighters fight crime, what do freedom fighters fight? ', 
	'Why do you often see a shoe lying on the side of the street? ', 
	'Why do we pay tolls on the freeway?', 
	'Why do banks charge you a \" non sufficient funds\" fee on money they already know you don\'t have? ', 
	'Does the reverse side also have a reverse side?', 
	'Do you think the Assassination Museum was created after JFK\'s assassination?', 
	'Where do forest rangers go to get away from it all? ', 
	'Why is a black light not black? ', 
	'Why is it when a door is open it\'s ajar but when a jar is open isn\'t not adoor? ', 
	'Why do they call a pear a pear if there is only one? ', 
	'Why is it called a Caesar\'s salad? Did he invent it? ', 
	'If it is tourist season, why can\'t we shoot them?', 
	'Since light travels faster than sound, isn\'t that why some people appear bright until you hear them speak? ', 
	'Do blind Eskimos have seeing -eye sled dogs?', 
	'If someone invented instant water, what would they mix it with? ', 
	'Why do old men wear their pants higher than young men do? ', 
	'If your born again do you have two belly buttons? ', 
	'Why do they say new and improved? It can\'t be new if it was improved can it?', 
	'Why did kamikaze pilots wear helmets? ', 
	'If you choke a Smurf what color would it turn? ', 
	'How does the guy who runs the snowplow get to work in the morning?', 
	'Why do we drive on parkways and park on driveways? ', 
	'If you got into a taxi and the driver started driving backward would the taxi driver end up owing you money? ', 
	'How do they get deer to cross at the yellow sign?', 
	'Why do we wait until a pig is dead to cure it? ', 
	'How much money, in pennies, is lying on the streets of the world?', 
	'Why do women wear such uncomfortable shoes? ', 
	'Why does the Indiana driver\'s license include in its list of possible restrictions \"B\" for \"Blind\"?', 
	'If a turtle doesn\'t have a shell is he homeless or naked? ', 
	'Why is it called a football when you really don\'t use your feet at all? ', 
	'Why does the psychic hotline ask for your credit card number? Shouldn\'t they already know it? ', 
	'Why do fat chance and slim chance mean the same thing? ', 
	'Isn\'t the best way to save face to keep the lower part shut? ', 
	'Do vegetarians eat animal crackers?', 
	'How does Elmo hear? Elmo has no ears?', 
	'Why are there interstate highways in Hawaii? ', 
	'Did Washington just flash a quarter for his ID?', 
	'Why is it that when you tell a person that there are 400 billion stars in the sky and he\'ll believe you, tell him a bench is wet and he has to touch it? ', 
	'If a tree falls in the forest and no one is around to see it do the other trees make fun of it? ', 
	'Is the grass really greener on the other side? ', 
	'Why is there only ONE monopolies commission? ', 
	'Why is an orange an orange but an apple not a red? ', 
	'If there is no God, who pops up the next Kleenex in the box? ', 
	'Is the glass half full or half empty?', 
	'If you set to work with a knife that will cut through anything and Tupperware that\'s guaranteed not to break, what happens?', 
	'How do I set my laser printer on stun gun?', 
	'Why do people look up when they think?', 
	'Why do we tie shoes to the back of newlywed\'s cars? ', 
	'Why don\'t we get dizzy from the world spinning so fast? ', 
	'Is it possible to be totally partial? ', 
	'If blind people wear sunglasses why don\'t deaf people wear ear muffs? ', 
	'Does a fish get cramps after eating?', 
	'What are preparations A-G? ', 
	'Why when you say a color a lot does it start to sound really strange? ', 
	'Do infants have as much fun in the infancy as adults do in their adultery?', 
	'What happened to the first 6 \"ups\"?', 
	'Why do doughnuts have holes? ', 
	'Do cemetery workers prefer the graveyard shift?', 
	'If you throw your pet cat out the window of your car does it bec0me cat litter? ', 
	'Why are cigarettes sold at gas stations if smoking is prohibited there? ', 
	'Why are cows milked from the right side? ', 
	'Why is it called a building when it\'s already built? ', 
	'Why isn\'t phonic spelled the way it sounds? ', 
	'Can fat people go skinny-dipping?', 
	'Why do we play in recitals and recite in plays? ', 
	'How does the Cheshire cat only show his smile?', 
	'Why did God give men nipples? ', 
	'Isn\'t Big Kid and oxymoron?', 
	'If trailer parks didn\'t exist would tornadoes exist? ', 
	'Why do they call them straight jackets when they are never straight?', 
	'Why do we have to dry raincoats? ', 
	'Why isn\'t \"palindrome\" spelled the same way backwards? ', 
	'If a man evolved from monkeys and apes, why do we still have monkeys and apes? ', 
	'Why do you have a hot water heater when you don\'t need to heat hot water? ', 
	'Just before someone gets nervous do they experience cocoons in their stomachs?', 
	'Does chewing gum lose its flavor on the bed post overnight?', 
	'Can your face actually freeze while making ugly faces?', 
	'Why do steam irons have a permanent press setting? ', 
	'Why do we itch? ', 
	'Why do phone companies give you a number to call if your phone doesn\'t work?', 
	'Would a fly with out wings be called a walk? ', 
	'When I erase a word with a pencil where does it go? ', 
	'How come you press harder on a remote when you know the battery is dead?', 
	'Why isn\'t there mouse flavored cat food? ', 
	'Why are they called apartments when they are stuck together? ', 
	'Why are most homes white? ', 
	'If the universe is everything, and scientists say that the universe is expanding what is it expanding into? ', 
	'Why don\'t we get goosebumps on our face? ', 
	'Why do brown eyes see better in the sun than blue eyes? ', 
	'Why does an alarm clock \"go off\" when it BEGINS ringing? ', 
	'Why goes glass eventually get thicker towards the bottom?', 
	'Why is jack a nickname for John? ', 
	'Why can\'t we make newspapers that don\'t smudge? ', 
	'Who really took the bite out of the Apple logo? ', 
	'If the #2 pencil is so popular, why is it still #2? ', 
	'How is it possible to have a civil war?', 
	'Why do roman paramedics refer to IV\'s as \"4\'s\"?', 
	'Will wearing short sleeve shirts show your support for the right to bare arms? ', 
	'Why do some ranchers put old boots on fence posts? ', 
	'Where do they get that awful music for ice-skating? ', 
	'If a person kills their clone is it murder or suicide?', 
	'Why are they called stands when they are made for sitting? ', 
	'If a book about failures doesn\'t sell, is it a success? ', 
	'Whose cruel idea was it for the word lisp to have a s in it? ', 
	'If vegetarians eat vegetables what do humanitarians eat? ', 
	'How do you tell when you are out of invisible ink?', 
	'How does one actually zip their lip?', 
	'When an elevator is overloaded with passengers who is criminally responsible? ', 
	'If the entire world is a stage, where is the audience sitting? ', 
	'When sign makers go on strike is there anything written on their signs? ', 
	'Why are toilet flush handles on the left side? ', 
	'Why do other people hear our voices different than we do? ', 
	'How does Kraft get the 5 ounces into every slice of American Singles?', 
	'How come superman can stop bullets with his chest but he always ducks when someone throw a gun at him?', 
	'Do hungry crows have ravenous appetites?', 
	'Why is it that when you are driving and looking for an address you turn the radio down? ', 
	'Why are there flotation devices under plane seats instead of parachutes? ', 
	'IF you\'re cross-eyed and have dyslexia can you read all right? ', 
	'If someone with multiple personalities threatens to kill himself, is it considered a hostage situation or a murder? ', 
	'Why is it that when you see someone in a cast or a brace you say ouch?', 
	'If it is zero degrees outside today and it is supposed to be twice as cold tomorrow, how cold is it going to be? ', 
	'What do you plant to grow a seedless watermelon?', 
	'Was the only reason God gave us a shin is to find things in the dark? ', 
	'Why are there 5 syllables in the word monosyllabic? ', 
	'Where are the germs that cause good breath? ', 
	'Why does unscented hairspray smell? ', 
	'What is Mother Goose\'s real first name? ', 
	'If one synchronized swimmer drowns do the rest have to drown too? ', 
	'Why does the minute hand on school clocks always click backward before advancing? ', 
	'If a stealth bomber crashes in a forest, will it make a sound? ', 
	'Why do your feet swell on airplanes? ', 
	'If pro is the opposite of con, is progress the opposite of congress? ', 
	'Shouldn\'t there be a shorter word for monosyllabic? ', 
	'If white wine goes with fish do white grapes go with sushi? ', 
	'Before they invented drawing boards what did they go back to?', 
	'Why do scientists call it research when they are looking for something new? ', 
	'If nothing ever sticks to Teflon, how do they get Teflon to stick to the pan? ', 
	'Are there seeing eye humans for blind dogs?', 
	'How come you never hear about grunted employees?', 
	'Why don\'t more psychics win the lottery? ', 
	'How many licks does it really take to get to the center of a tootsie pop? ', 
	'How do they unclog mail chutes in skyscrapers?', 
	'If I break the laws of Physics do I go to jail?', 
	'What is the purpose of the red string on Band-Aid brand adhesive packages? ', 
	'What causes the holes in Swiss cheese? ', 
	'Why is it that when you transport something by car it is called a shipment but when you transport something by ship it is called cargo? ', 
	'Do they have reserved parking for non-handicap people at the Special Olympics?', 
	'Why is the alphabet in that order? Is it because of that song? ', 
	'Why is there an expiration date on SOUR cream? ', 
	'What was the best thing before sliced bread? ', 
	'Why is it when to planes almost hit each other it is called a near miss? Shouldn\'t it be called a near hit? ', 
	'Why can\'t you find fresh sardines in a fish market? ', 
	'Which fruits are in Juicy Fruit? ', 
	'If you can\'t drink and drive why do you need a driver\'s license to buy liquor, and why do bars have parking lots? ', 
	'If you don\'t repair your brakes right away should you make your horn louder? ', 
	'How many turtles does it take to make one can of turtle wax? ', 
	'Why are jeans so hard to fit into? ', 
	'What do little birdies see if they get knocked unconscious? ', 
	'Why aren\'t there seat belts in buses and taxicabs? ', 
	'Isn\'t it a bit unnerving that doctors call what they do \"practice\"?', 
	'Why do they call it the department of interior when they are in charge of everything outdoors? ', 
	'Why is yawning contagious? ', 
	'Why do we sing Take Me Out To the Ball Game if we are already there? ', 
	'Why do we but a product that takes 2000 flushes to get rid of? ', 
	'If taught do gorillas really understand sign language? ', 
	'Why is toilet paper scented? ', 
	'Why doesn\'t Tarzan have a beard? ', 
	'Who don\'t penguins in Antarctica ever get frostbite? ', 
	'Do boxer shorts box?', 
	'How much deeper would the ocean be if sponges didn\'t grow in it? ', 
	'Have you ever imagined a world with no hypothetical situations?', 
	'Why does soda taste better in a small bottle than in a large bottle or in a can? ', 
	'If a mute swears does his mother was his hands with soap? ', 
	'What do you do when you see an endangered animal that is eating an endangered plant? ', 
	'If you have an open mind is there a chance your brain might fall out? ', 
	'Is there another word for synonym? ', 
	'Why does X stand for kiss and O stand for hugs? ', 
	'Where does the lost sock in the washer and dryer go? ', 
	'Does fuzzy logic tickle?', 
	'Why do bananas grow upward and all other fruits grow downward? ', 
	'Where do swear words come from? ', 
	'Why doesn\'t onomatopoeia sound like what it is? ', 
	'Why do people who know the least know it the loudest? ', 
	'Why do psychics have to ask for your name? ', 
	'If the speed of light is 186,000 miles per second, what is the speed of dark? ', 
	'Why doesn\'t glue stick to the inside of the bottle? ', 
	'How do they get the cream in the Twinkie?', 
	'Why do corn flakes and Sugar frosted flakes have the save number of calories per serving? ', 
	'Why does slow down and slow up mean the same thing? ', 
	'What does the Q in Q-tip stand for?', 
	'Why are elections held on Tuesdays? ', 
	'Instead of talking to your plants, if you yelled at them would the still grow? Only to be troubled and insecure? ', 
	'What happens when none of your bees wax? ', 
	'Why do they sterilize the needles for lethal injection? ', 
	'Do little angels have car seats in their chariots in heaven?', 
	'What\'s another word for thesaurus? ', 
	'Why are school buses painted yellow? ', 
	'What does Geronimo yell when he jumps out of a plane? '
);


/*
	GetStatement( ) is the primary function.  It assumes the following:
	
	1.  The HTML file contains a form named "statementform".
	2.  Within the statement form, there is a textarea or textbox named "statement".               */

function GetStatement(outputtype) //modified by javascriptkit.com to either write out result or set innerHTML prop
{
	if(++Number > Statements.length - 1) Number = 0;
	if (outputtype==0)
	document.write(Statements[Number])
	else if (document.getElementById)
	document.getElementById("ponder").innerHTML=Statements[Number];
}


//  The GetRandomNumber( ) function extracts a random number within a given range.


function GetRandomNumber(lbound, ubound) 
{
	return (Math.floor(Math.random() * (ubound - lbound)) + lbound);
}


// The Number variable keeps track of which statement to display.  It will start at a random point.                

var Number = GetRandomNumber(0, Statements.length - 1);






